# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_thing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
